In [155]:
import numpy as np

In [156]:
def normalize(feature):
  
    # ++++++++++++++++++++++++++++++++++++++++++++++++++
    # complete the blanks
    #

    feature_normalize = np.array([(feature[:,0] - np.mean(feature[:,0])) / np.std(feature[:,0]), (feature[:,1] - np.mean(feature[:,1])) / np.std(feature[:,1])]).T

    #
    # ++++++++++++++++++++++++++++++++++++++++++++++++++
    
    return feature_normalize

In [157]:
def compute_covariance(feature):
  
    # ++++++++++++++++++++++++++++++++++++++++++++++++++
    # complete the blanks
    #
    # feature is already normalized

    Sigma = np.zeros((2, 2))

    for i in range(feature.shape[0]):
        Sigma += np.outer(feature[i], feature[i])

    Sigma = Sigma / feature.shape[0]


    #
    # ++++++++++++++++++++++++++++++++++++++++++++++++++

    return Sigma

In [158]:
def compute_principal_component(feature):
  
    # ++++++++++++++++++++++++++++++++++++++++++++++++++
    # complete the blanks
    #

    Sigma = compute_covariance(feature)

    eigen_value, eigen_vector = np.linalg.eig(Sigma)

    sort_idx = np.argsort(eigen_value)[::-1]
    principal_component_1, principal_component_2 = eigen_value[sort_idx] * eigen_vector[:, sort_idx]



    #
    # ++++++++++++++++++++++++++++++++++++++++++++++++++
     
    return (principal_component_1, principal_component_2)

In [159]:
A = np.array([[1, 2], [4, 5], [7, 8]])
A = normalize(A)

print(compute_principal_component(A))



# eigen_value, eigen_vector = np.linalg.eig(compute_covariance(A))

# result = np.argsort(eigen_value)

# print(eigen_value)
# print(eigen_vector)

# print(eigen_value[result])
# print(eigen_vector[result])

# feature_1 = eigen_vector[result] * eigen_value[result]
# print(eigen_value[result])
# print(feature_1)


# print(eigen_value)
# print("======")
# print(eigen_value.argsort())
# print("======")
# print(eigen_value[eigen_value.argsort()])
# # print(eigen_vector)


    

[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
(array([1.41421356e+00, 1.57009246e-16]), array([ 1.41421356e+00, -1.57009246e-16]))
